
version: 2

models:
  - name: prd_partneraccounts
    description: "Converting Raw Partner Data to Prod"
    #columns:
    #  - name: id
    #    description: "The primary key for this table"
    #    tests:
    #      - unique
    #      - not_null
